services:
  cgp_miner:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    volumes:
      - ${HOME}/.bittensor/wallets/${COLDKEY_NAME}/coldkeypub.txt:/root/.bittensor/wallets/${COLDKEY_NAME}/coldkeypub.txt
      - ${HOME}/.bittensor/wallets/${COLDKEY_NAME}/hotkeys/${HOTKEY_NAME}:/root/.bittensor/wallets/${COLDKEY_NAME}/hotkeys/${HOTKEY_NAME}
      - ${HOME}/.bittensor/logs:/root/.bittensor/logs