services:
  cgp_miner:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    volumes:
      - ~/.bittensor/wallets/${COLDKEY_NAME}/coldkeypub.txt:~/.bittensor/wallets/${COLDKEY_NAME}/coldkeypub.txt
      - ~/.bittensor/wallets/${COLDKEY_NAME}/hotkeys/${HOTKEY_NAME}:~/.bittensor/wallets/${COLDKEY_NAME}/hotkeys/${HOTKEY_NAME}
      - ~/.bittensor/logs:~/.bittensor/logs