version: "3.8"

services:
  cgp_miner:
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env

    ports:
      - "${PORT}:${PORT}"

    restart: on-failure

    volumes:
      - ${HOME}/.bittensor/wallets/${COLDKEY_NAME}/hotkeys/${HOTKEY_NAME}:/home/appuser/.bittensor/wallets/${COLDKEY_NAME}/hotkeys/${HOTKEY_NAME}
      - ${HOME}/.bittensor/wallets/${COLDKEY_NAME}/coldkeypub.txt:/home/appuser/.bittensor/wallets/${COLDKEY_NAME}/coldkeypub.txt
      - ${HOME}/.bittensor/logs:/home/appuser/.bittensor/logs