services:
  cgp_miner:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    restart: on-failure
    volumes:
      - ${HOME}/.bittensor/wallets/${COLDKEY_NAME}/coldkeypub.txt:/home/appuser/.bittensor/wallets/${COLDKEY_NAME}/coldkeypub.txt
      - ${HOME}/.bittensor/wallets/${COLDKEY_NAME}/hotkeys/${HOTKEY_NAME}:/home/appuser/.bittensor/wallets/${COLDKEY_NAME}/hotkeys/${HOTKEY_NAME}
      - ${HOME}/.bittensor/logs:/home/appuser/.bittensor/logs
    # Sets the keys to read-only for non-owner users, allowing Docker access, then runs the entrypoint script.
    entrypoint:   
    - /bin/sh
    - -c
    - |
      chmod 644 /home/appuser/.bittensor/wallets/${COLDKEY_NAME}/coldkeypub.txt
      chmod 644 /home/appuser/.bittensor/wallets/${COLDKEY_NAME}/hotkeys/${HOTKEY_NAME}
      exec /entrypoint.sh
